### PR TITLE
Wayfinding and learning ramp

### PR DESCRIPTION
**Pull request by tsibley**
Several interrelated changes to the TOC tree organization and learning ramp starting from the landing page that I think add up to overall improvements to wayfinding. See commit messages for details. May be easier to review by comparing the preview site with the live site.

Incorporates #71.

### CODE REVIEW

**Review by huddlej — APPROVED** [review]
This is a big improvement to the sidebar navigation and the flow for new users. I actually like "parts of a whole". For me, it suggested the idea that Nextstrain is "greater than the sum of its parts".

I don't have any major feedback on the content or reorganization. I prefer titles with an action statement ("Install Nextstrain") over those with "-ing" ("Installing Nextstrain"). I don't know what value the "-ing" adds, but I also don't feel strongly enough to push for their elimination.

Let's merge this! 🎉

**Comment by tsibley** [comment]
> I actually like "parts of a whole". For me, it suggested the idea that Nextstrain is "greater than the sum of its parts".

That was what was in my head! so I guess it's doing a good job of communicating or our heads are close in connotation-space. :upside_down_face: 

> I prefer titles with an action statement ("Install Nextstrain") over those with "-ing" ("Installing Nextstrain"). I don't know what value the "-ing" adds, but I also don't feel strongly enough to push for their elimination.

I'm largely ambivalent here but went with -ing because it seemed like it was already the more-used form. I'm 100% ok with standardizing ~everything to the non-ing form in a future commit if you or someone else wanted to do that. Either way, I do think consistency helps here, esp. in the context of the sidebar.

**Comment by tsibley** [comment]
Rebased after merging #74 to see the CI job pass.

**Comment by tsibley** [comment]
I realized I forgot to follow up on the redirects I meant to add for pages that moved or went away, so I just setup the following [*page redirects*](https://docs.readthedocs.io/en/stable/user-defined-redirects.html#page-redirects) on RTD:

From | To
---- | --
/install-nextstrain.html | /install.html
/learn/about-nextstrain.html | /learn/about.html
/reference/formats/data-formats.html | /reference/data-formats.html
/reference/formats/index.html  | /reference/data-formats.html
/reference/formats/  | /reference/data-formats.html
/learn/ | /
/tutorials/ | /
/guides/ | /
/reference/ | /
/learn/index.html | /index.html
/tutorials/index.html | /index.html
/guides/index.html | /index.html
/reference/index.html | /index.html

**Pull request merged**
