### PR TITLE
Replace sphinx_copybutton with nextstrain.sphinx.theme

### PR DESCRIPTION
**Pull request by victorlin**
## Description of proposed changes

The new extension already has sphinx_copybutton pre-installed and configured.

## Related issue(s)

https://github.com/nextstrain/sphinx-theme/issues/30

## Testing

- [ ] copy button works on RTD preview build

### CODE REVIEW

**Comment by tsibley** [comment]
Should we update the dep declaration to `nextstrain-sphinx-theme >=2022.5` to be safe?

**Comment by victorlin** [comment]
Oh good point!

**Comment by victorlin** [comment]
Ok, should be good on all PRs now (and created a new one for CLI: https://github.com/nextstrain/cli/pull/199)

**Review by tsibley — APPROVED** [review]
Non-blocking, but I would squash these two commits together since they're part of the same change (one depends on the other and vice versa).

**Pull request merged**
