### PR TITLE
Versioned resources copyedits

### PR DESCRIPTION
**Pull request by tsibley**
See commit messages for details.

Related to #177.

## Checklist

- [x] Checks pass

### CODE REVIEW

**Comment by tsibley** [comment]
@jameshadfield Just a few small edits for consistency which I think are improvements. Overall the document you wrote is a great compact and punchy guide-by-example of the dated snapshots feature!

**Comment by tsibley** [comment]
Ah, I'll fix that warning tomorrow.

**Review by jameshadfield — COMMENTED** [review]
Thanks! Nice to have someone else's eyes on these things.

First three commits seem good to me.

I'm ambivalent about "snapshot" (yes I realise I used it in the overview paragraph) so it'd be good to get some other opinions from the team about what language is best used here. In the (internal facing) code I use "version" and don't want to change that.

**Comment by tsibley** [comment]
> First three commits seem good to me.

I've merged those (merge commit be6d3f5779fc73aa5f96143a50bbbe704404c105). Will wait for the remaining two.

**Comment by tsibley** [comment]
Conclusion at the biweekly all-hands discussion just now was "snapshot", so I've merged.

**Pull request merged**
