### PR TITLE
reference: Document how to configure/modify CA certificate trust stores

### PR DESCRIPTION
**Pull request by tsibley**
This information is a distillation of guidance and assistance I've provided to CDC and other downstream users over the years.  I extracted it from my various notes and recollections and verified some specific behaviour anew.  An official reference page will be useful for pointing users to in the future, and serves as a collection point for future recommendations/information uncovered in troubleshooting sessions.

Related-to: <https://github.com/nextstrain/ncov/issues/1055>
Related-to: <https://github.com/nextstrain/nextclade/issues/726>

## Checklist

- [ ] Checks pass

### CODE REVIEW

**Comment by tsibley** [comment]
[Preview](https://nextstrain--229.org.readthedocs.build/en/229/reference/ca-certificates.html)

**Review by genehack — APPROVED** [review]
😵‍💫 this should be an exhibit in the "computers were a mistake" display

**Comment by tsibley** [comment]
Yes. Yes, indeed. Also, it gets worse. More updates tomorrow (my SSH key is sitting upstairs, and I'm not going to fetch it and then come back down just to push tonight).

Anyway, a thought I can't get out of my head tonight: I, without a doubt, have dozens of (different!) copies of Mozilla's CA certs on my computer, all used by different bits of software at different times. It's a wonder anything works at all.

**Review by victorlin — APPROVED** [review]
🙌

**Pull request merged**
